name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
  
  
      
      - name: Install Dependencies and Build API
        run: |
          cd api
          npm install
          sudo npm run build
          sudo npm start

      - name: Run Tests
        run: |
          cd my-app
          sudo npm install
          sudo npm run build




